### ISSUE TITLE
Is it posible to use goldenview without ruby support?

### ISSUE THREAD

**Issue by dagadbm** [zhaocai/GoldenView.Vim#26]
I installed ruby on my windows machine but to no avail.

This is the most decent tile manager i saw so far for vim. 
Is there a way to make this work only with VimL?

**Comment by ReneFroger** [comment]
Yes, with Emacs it is possible with golden-ratio.el I believe. You could test it first with Spacemacs.

**Comment by dagadbm** [comment]
I use vim.
Emacs is way to slow on windows unfortunately.
